package com.restaurantebot;

public enum EstadoConversa {
    INICIO,
    AGUARDANDO_INICIAR_MARMITA,
    AGUARDANDO_TAMANHO_MARMITA,
    AGUARDANDO_OPCAO_CATEGORIA,
    AGUARDANDO_OUTRA_MARMITA,
    AGUARDANDO_INICIAR_BEBIDA,
    AGUARDANDO_ESCOLHA_BEBIDA,
    AGUARDANDO_OUTRA_BEBIDA,
    AGUARDANDO_ACAO_RESUMO,
    AGUARDANDO_REMOCAO_ITEM,
    AGUARDANDO_TIPO_RECEBIMENTO,
    AGUARDANDO_ENDERECO,
    AGUARDANDO_NOME_ENTREGA,
    AGUARDANDO_NOME_RETIRADA,
    AGUARDANDO_PAGAMENTO,
    EM_ATENDIMENTO
}
